-----------------------------------Inserts-----------------------------
drop table test_auto;

create table test_auto(
    test_id number generated by default on null as identity,
    constraint test primary key(test_id)
);

insert into test_auto values (20);

select * from test_auto;


--Recommended way to do an insert 
--which is list the columns in the same order that they appear in in the table
insert into departments(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
values                 (71, 'Development 1', 100, 1700);


--Je kan dit ook doen, yk, zonder actually te specifyen in welke rows je insert, maar als je dit doet, dan zeg je basically
--dat je in elke column van die table gaat inserten
insert into DEPARTMENTS values(72, 'Development 2', 100, 1700);


--You can also change the order in which the columns appear, maar dan moeten die order van die values ook matchen met wat je hebt gezet
insert into DEPARTMENTS(DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID, DEPARTMENT_ID)
            values      ('Development 3', 100, 1700, 73);




--Inserting rows with null values
--implicit:plaats het niet in je insert lijst en dan gaat het automatisch null voor je zetten. Also make sure dat ze nullable zijn ofc
insert into DEPARTMENTS(DEPARTMENT_ID, DEPARTMENT_NAME)
                values (74, 'Development 4');


--explicit waarbij je zelf null zet
insert into DEPARTMENTS(DEPARTMENT_ID, DEPARTMENT_NAME,MANAGER_ID, LOCATION_ID)
            VALUES      (75, 'Development 5', null, null);



--Je kan substitution variables gebruiken
insert into departments(DEPARTMENT_ID, DEPARTMENT_NAME)
            VALUES      (&dept_id, '&dept_name');


--You can make inserts using a subquery
drop table xx_emp;

create table xx_emp(
    empno number,
    fname varchar2(100),
    salary number
);  

select * from xx_emp;


--Als je values zo insert hoef je geen values keyword te gebruike
insert into xx_emp(empno, fname, salary)
select EMPLOYEE_ID, FIRST_NAME, SALARY from EMPLOYEES;


--zo kan het ook
insert INTO EMP_COPY(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID)
select 102, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID
from EMPLOYEES where EMPLOYEE_ID=101;







--Multiple inserts using one statement(not a multitable insert!)
commit;
insert into EMP_COPY(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID)
VALUES              (1000, 'Sameer', 'Kewal', 'skewal@test.com', '115', to_date('01-MAY-2002', 'DD-MON-YYYY'), 'IT_PROG', 1000, 1, 101),
                    (1001, 'Jennifer', 'Amogus', 'jamogus@test.com', '911', to_date('09-NOV-2000', 'DD-MON-YYYY'), 'IT_PROG', 1000, 1, 101);
                    


-------------------------Common Errors-------------------------------


--Primary keys mogen geen duplicates zijn en moeten ook geen null zijn
--Therefore zou dit logisch niet kunnen:
--Unique Constraint PK violated
insert into departments(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
VALUES                  (10, 'Development 1', 100, 1700);


--Inserting FK value that doesnt exist in the parent table
--Integrity constraint violated
insert into DEPARTMENTS(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
VALUES                  (5, 'Development 1', 100, 1);


--Dont even have to show this but mismatching datatype
--                                value too long






